### ISSUE TITLE
mongo vs mongoose

### ISSUE THREAD

**Issue by strugart** [strugart/nodetest#4]
@mjlescano el autor dice en el unico issue del repo que el tutorial esta roto ya que debería usar mongoose. 
yo ahora no puedo usar la db local, cuando hago npm start me dice que var db = monk(db path) no es una variable no es valida (o similar)
mas allá de cambiar el json y la app.js, algun cambio mas seria necesario?
gracias.

**Comment by mjlescano** [comment]
Pasate algun link o copiate alguna linea de código, ni idea dónde te referis :)

Si no queres tener que abrir un server de mongo local, podes usar https://mlab.com, que tienen DBs de prueba gratis.

**Comment by mjlescano** [comment]
También, usá el botón de "insert code", asi podes pegar código y te queda con `éste` estilo y se puede leer mejor :D

_**Más info:** https://guides.github.com/features/mastering-markdown/_

**Comment by mjlescano** [comment]
Ah! ahí lo ví. [Acá](https://github.com/strugart/nodetest/blob/master/app.js#L10) te falta un `require`.

Tiene que ser:
```javascript
var monk = require('monk');
```

**Comment by strugart** [comment]
el code esta en app.js del root del repo (es correcto decir root?):
``
//New` code
var mongo = require('mongodb');
var monk = ('monk');
var db = monk('localhost:27017/nodetest1');
